// AUTO-GENERATED by scripts/agent-keygen.ts. Не править руками.
// Публичный ключ для верификации agent.js при self-update.
// Приватник — secrets/agent-signing-key.pem (gitignored).

export const AGENT_PUBLIC_KEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA1gf34NSYIQc+6Y9wBkBNCRjs2v/uZ2dMebnyck5ATj0=\n-----END PUBLIC KEY-----\n";
