/**
 * Генерит Ed25519 keypair для подписи agent.js.
 *
 * Usage:
 *   npx tsx scripts/agent-keygen.ts
 *
 * Артефакты:
 *   • secrets/agent-signing-key.pem — приватник (PKCS8 PEM). НЕ в гит.
 *   • apps/agent/src/agent-public-key.ts — публичный ключ (SPKI PEM, base64-one-line).
 *     Закоммитить и пересобрать agent.
 *
 * Этот ключ — единственная защита от того, что компрометация мастера превращается
 * в massive supply-chain attack на все агенты. Приватник держим оффлайн (laptop
 * owner'a или KMS), мастер только раздаёт уже подписанный agent.js + .sig.
 *
 * Если ты ротируешь ключ, все агенты со старым публичным ключом перестанут
 * апдейтиться до того, как переустановятся вручную. Это by design.
 */
import { generateKeyPairSync } from 'node:crypto';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const secretsDir = resolve(repoRoot, 'secrets');
const privPath = resolve(secretsDir, 'agent-signing-key.pem');
const pubTsPath = resolve(repoRoot, 'apps/agent/src/agent-public-key.ts');

if (existsSync(privPath) && !process.argv.includes('--force')) {
  console.error(`refuse to overwrite existing ${privPath}`);
  console.error(`pass --force if you really want to rotate (will brick all installed agents)`);
  process.exit(1);
}

const { publicKey, privateKey } = generateKeyPairSync('ed25519');
const privPem = privateKey.export({ format: 'pem', type: 'pkcs8' }).toString();
const pubPem = publicKey.export({ format: 'pem', type: 'spki' }).toString();

mkdirSync(secretsDir, { recursive: true });
writeFileSync(privPath, privPem, { mode: 0o600 });

const tsContent = `// AUTO-GENERATED by scripts/agent-keygen.ts. Не править руками.
// Публичный ключ для верификации agent.js при self-update.
// Приватник — secrets/agent-signing-key.pem (gitignored).

export const AGENT_PUBLIC_KEY_PEM = ${JSON.stringify(pubPem)};
`;
writeFileSync(pubTsPath, tsContent);

console.log(`✓ private key → ${privPath} (mode 0600, gitignored)`);
console.log(`✓ public key  → ${pubTsPath} (commit this)`);
console.log(``);
console.log(`Next:`);
console.log(`  npm run build -w apps/agent   # build + sign agent.js`);
console.log(`  git add ${pubTsPath}`);
console.log(`  git commit -m "rotate agent signing key"`);
